### Class exercise: table
![](images/numpy_slice_ex.png)
- on the above image find the 5 different slicings using only the array slicing notation

In [63]:
import numpy as np

a = np.arange(10, 30).reshape(4, 5)

yellow = a[0, 0]
turkis = a[:, 1:-1:2]
green = a[0:3, 2]
blue = a[::2, 4]
red = a[0, 1:4:1]

print("Yellow:", yellow, "\nTurkis:\n", turkis, "\nGreen:\n", green, "\nBlue:\n", blue, "\nRed:\n", red)

Yellow: 10 
Turkis:
 [[11 13]
 [16 18]
 [21 23]
 [26 28]] 
Green:
 [12 17 22] 
Blue:
 [14 24] 
Red:
 [11 12 13]


### Class exercise: masking
- For the dataset: `data = np.arange(1,101).reshape(10,10)`
  - apply a mask that will return only the even numbers
  - using `np.where()` return only numbers that ends with 6

In [72]:
data = np.arange(1,101).reshape(10,10)

#even_nums = np.where(data % 2 == 0)

print(even_nums)
